name: Run tests

on:
  pull_request:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            # Install a specific version of uv.
            version: "0.5.9"
            enable-cache: true

      - name: Check styling
        run: uv run ruff format --check src/lanfactory

      - name: Linting
        run: uv run ruff check src/lanfactory

    #   - name: Run pytest
    #     run: pytest

      # - name: Build Docs
      #   run: mkdocs build
